### ISSUE TITLE
ModPlanner Command & Functionality

### ISSUE THREAD

**Issue by LongLeCE** [AY1920S1-CS2113T-F10-1/main#92] opened 2019-10-15 11:45 UTC
*Refer to #89 for Argparse4jWrapper's implementation and how to add command*

## ModPlanner's current working/implemented/prospective/prototype commands/features:
*Update: Updated CCA commands references*

- Add module: Implemented in **SearchThenAddCommand**
```
add [moduleCode]
```
- Remove module: Implemented in **RemoveModCommand**
```
remove [index]
```
- Show modules: Implemented in **ShowModuleCommand**
```
show
```
- End current instance: Implemented in **EndCommand**
```
bye
```
- Add CCA: Implemented in **AddCcaCommand**
```
addCca [name] --begin [beginTime] --end [endTime] --dayOfWeek[dayOfWeek]
```
- Remove CCA: Implemented in **RemoveCcaCommand**
```
removeCca [index]
```
- Show CCAs: Implemented in **ShowCcaCommand**
```
showCca
```
- Add schedule to CCA: Implemented in **AddCcaScheduleCommand**
```
scheduleCca [index] --begin [beginTime] --end [endTime] --dayOfWeek[dayOfWeek]
```
@namiwa @kyawtsan99 @andrewleow97 @e0313687 Feel free to comment below if you need any additional feature/command or implemented any other functionality for ModPlanner

**Comment by namiwa** [comment] 2019-11-07 06:28
Closed as implemented as intended for v1.4

**Closed by namiwa** 2019-11-07 06:28 UTC
Labels: priority.Medium, status.Ongoing, type.Tracker
